/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ren (https://sketchfab.com/IrenaSantoso)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/headphones-ef7799bcdba043238c4deef9d2832730
title: Headphones
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame} from "@react-three/fiber";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF("/headphones.gltf");

	useFrame(({ clock }) => {
		const elapseTime = clock.getElapsedTime();
		group.current.rotation.y = elapseTime / 5;
	});
	return (
		<>
			<ambientLight intensity={1} />
			<group
				ref={group}
				{...props}
				dispose={null}
				scale={2}
				position={[0, -1, 0]}>
				<group rotation={[-Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.Object_2.geometry}
						material={materials.blinn1SG}
					/>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/headphones.gltf");
