/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import {
	useGLTF,
	useAnimations,
	Stars,
} from "@react-three/drei";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, animations } = useGLTF("/animatedAstronaut.gltf");
	const { actions } = useAnimations(animations, group);

	// console.log(actions)
	useEffect(() => {
		actions?.floating.play();
	});

	return (
		<>
			
			{/* Sun light simulation  */}
			<pointLight color="#f6f3ea" position={[2, 0, 5]} intensity={1.2} />
			<Stars
				radius={300}
				depth={60}
				count={20000}
				factor={7}
				fade={true}
			/>
			<group ref={group} {...props} dispose={null}>
				<group>
					<group
						name="RootNode0"
						scale={0.02}
						position={[0, -3.5, 0]}>
						<group name="geo1">
							<group name="astronaut2">
								<skinnedMesh
									name="mesh_0"
									geometry={nodes.mesh_0.geometry}
									material={nodes.mesh_0.material}
									skeleton={nodes.mesh_0.skeleton}
								/>
								<skinnedMesh
									name="mesh_1"
									geometry={nodes.mesh_1.geometry}
									material={nodes.mesh_1.material}
									skeleton={nodes.mesh_1.skeleton}
								/>
								<skinnedMesh
									name="mesh_2"
									geometry={nodes.mesh_2.geometry}
									material={nodes.mesh_2.material}
									skeleton={nodes.mesh_2.skeleton}
								/>
							</group>
						</group>
						<group name="skeletal3">
							<primitive object={nodes.Root4} />
						</group>
					</group>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/animatedAstronaut.gltf");
