/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JonnyMANSON (https://sketchfab.com/JonnyMANSON)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-mixamo-retextured-model-62990b050faf48dd8590d5d15872857c
title: Free Mixamo retextured Model
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";


export default function Model({ ...props }) {
  const group = useRef();
  const pointLight = useRef();
	const { nodes, materials, animations } = useGLTF("/mixamo.gltf");
	const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
    actions["mixamo.com"].play();
  })

  useFrame(({ clock }) => {
    const elapseTime = clock.getElapsedTime();
    pointLight.current.rotation.y = elapseTime /8
  })
	return (
		<>
			<pointLight
				color="#90EE90"
				position={[2, 0, 5]}
				intensity={1.2}
				ref={pointLight}
			/>
			<ambientLight intensity={1} />
			<group
				ref={group}
				{...props}
				dispose={null}
				position={[0, -3.2, 4]}>
				<group name="Sketchfab_Scene">
					<group
						name="Sketchfab_model"
						rotation={[-Math.PI / 2, 0, 0]}
						scale={0.02}>
						<group
							name="e779cecba394439eb4f3b40699d8d016fbx"
							rotation={[Math.PI / 2, 0, 0]}>
							<group name="Object_2">
								<group name="RootNode">
									<group name="Object_4">
										<primitive object={nodes._rootJoint} />
										<skinnedMesh
											name="Object_6"
											geometry={nodes.Object_6.geometry}
											material={materials.Ch44_Body}
											skeleton={nodes.Object_6.skeleton}
										/>
										<skinnedMesh
											name="Object_7"
											geometry={nodes.Object_7.geometry}
											material={materials.Ch44_body1}
											skeleton={nodes.Object_7.skeleton}
										/>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/mixamo.gltf");
