/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mikita_Hubanau (https://sketchfab.com/Mikita_Hubanau)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lost-robot-5a5c314a82864818a3fa5a0f71b17990
title: Lost robot
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/robot.gltf");
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions["Animation"].play();
	});

	useFrame(({ clock }) => {
		const elapseTime = clock.getElapsedTime();
		group.current.rotation.y = elapseTime / 10;
	});
	return (
		<>
			<group
				ref={group}
				{...props}
				dispose={null}
				scale={0.04}
				position={[0, -2, 0]}>
				<group name="Sketchfab_Scene">
					<group
						name="Sketchfab_model"
						rotation={[-Math.PI / 2, 0, 0]}>
						<group name="root">
							<group
								name="GLTF_SceneRootNode"
								rotation={[Math.PI / 2, 0, 0]}>
								<group
									name="Plane_13"
									position={[1.74, 63.32, -37.51]}
									rotation={[0, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_26"
										geometry={nodes.Object_26.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane001_14"
									position={[57.85, 33.04, 73.42]}
									scale={0.31}>
									<mesh
										name="Object_28"
										geometry={nodes.Object_28.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane002_15"
									position={[69.08, 33.25, 19.37]}
									rotation={[-0.01, 0.01, 0]}
									scale={0.31}>
									<mesh
										name="Object_30"
										geometry={nodes.Object_30.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane003_16"
									position={[92.86, 32.32, -15.17]}
									scale={0.31}>
									<mesh
										name="Object_32"
										geometry={nodes.Object_32.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane004_17"
									position={[30.67, 65.47, 56.26]}
									scale={0.31}>
									<mesh
										name="Object_34"
										geometry={nodes.Object_34.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane005_18"
									position={[82.24, 58.91, -33.3]}
									rotation={[-0.01, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_36"
										geometry={nodes.Object_36.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane006_19"
									position={[44.66, 70.55, -12.69]}
									rotation={[-0.01, 0.01, 0]}
									scale={0.3}>
									<mesh
										name="Object_38"
										geometry={nodes.Object_38.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane007_20"
									position={[47.8, 53.95, -14.12]}
									rotation={[0, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_40"
										geometry={nodes.Object_40.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane008_21"
									position={[26.73, 62.14, 0.09]}
									rotation={[0, 0, -0.01]}
									scale={0.31}>
									<mesh
										name="Object_42"
										geometry={nodes.Object_42.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane009_22"
									position={[36.2, 51.67, 4.72]}
									rotation={[0, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_44"
										geometry={nodes.Object_44.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane010_23"
									position={[26.15, 58.31, -24.46]}
									rotation={[-0.01, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_46"
										geometry={nodes.Object_46.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane012_24"
									position={[-20.86, 83.65, -34.65]}
									rotation={[-0.01, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_48"
										geometry={nodes.Object_48.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane013_25"
									position={[-37.31, 67.82, -4.28]}
									scale={0.31}>
									<mesh
										name="Object_50"
										geometry={nodes.Object_50.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane014_26"
									position={[-46.18, 50.71, -23.88]}
									scale={0.3}>
									<mesh
										name="Object_52"
										geometry={nodes.Object_52.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane015_27"
									position={[-49.39, 62.61, -38.92]}
									scale={0.31}>
									<mesh
										name="Object_54"
										geometry={nodes.Object_54.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane016_28"
									position={[-58.2, 68.52, -7.57]}
									rotation={[0.01, 0, 0]}
									scale={0.31}>
									<mesh
										name="Object_56"
										geometry={nodes.Object_56.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="Plane017_29"
									position={[-59.85, 42.11, -37]}
									rotation={[0, 0, 0]}
									scale={0.3}>
									<mesh
										name="Object_58"
										geometry={nodes.Object_58.geometry}
										material={materials["emission.001"]}
									/>
								</group>
								<group
									name="butterfly_6"
									position={[21.2, 55.19, 34.78]}
									rotation={[0, -0.85, 0]}
									scale={6.57}>
									<group name="GLTF_created_0">
										<primitive
											object={
												nodes.GLTF_created_0_rootJoint
											}
										/>
										<skinnedMesh
											name="Object_7"
											geometry={nodes.Object_7.geometry}
											material={materials.butterfly}
											skeleton={nodes.Object_7.skeleton}
										/>
									</group>
								</group>
								<group
									name="Cube_7"
									position={[-0.48, 59.98, 0.7]}
									scale={[-174.94, 174.94, 174.94]}>
									<mesh
										name="Object_14"
										geometry={nodes.Object_14.geometry}
										material={materials.Sphere}
									/>
								</group>
								{/* <group name="Light_8" position={[-76.03, 179.41, 51.88]} rotation={[1.19, 1.06, -1.61]} scale={0.38}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.002']} />
              </group> */}
								<group
									name="Tree_main_9"
									position={[0, 38.15, 0]}
									scale={0.42}>
									<mesh
										name="Object_18"
										geometry={nodes.Object_18.geometry}
										material={
											materials.Tree_main_and_grass_robot
										}
									/>
								</group>
								<group
									name="Tree_up_10"
									position={[-5.91, 116.3, 4.8]}
									scale={0.08}>
									<mesh
										name="Object_20"
										geometry={nodes.Object_20.geometry}
										material={materials.Tree_up}
									/>
								</group>
								<group
									name="Robot_11"
									rotation={[Math.PI / 2, 0, 0]}>
									<mesh
										name="Object_22"
										geometry={nodes.Object_22.geometry}
										material={materials.Robot}
									/>
								</group>
								<group
									name="grass_main_12"
									position={[0, 38.97, 0]}
									scale={0.1}>
									<mesh
										name="Object_24"
										geometry={nodes.Object_24.geometry}
										material={materials.Grass_down}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/robot.gltf");
